-- Spatial domain baseline for the smart agriculture platform.
-- This file is intentionally additive: it keeps crm.agri_feature as the
-- shared spatial index entry and moves strong business fields into detail
-- tables.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS crm;

-- ---------------------------------------------------------------------------
-- Shared agri_feature upgrades
-- ---------------------------------------------------------------------------

ALTER TABLE IF EXISTS crm.agri_feature
  ADD COLUMN IF NOT EXISTS farm_id bigint,
  ADD COLUMN IF NOT EXISTS parcel_id bigint,
  ADD COLUMN IF NOT EXISTS owner_org_id bigint,
  ADD COLUMN IF NOT EXISTS bbox geometry(Polygon, 4326),
  ADD COLUMN IF NOT EXISTS created_by bigint,
  ADD COLUMN IF NOT EXISTS updated_by bigint;

CREATE INDEX IF NOT EXISTS idx_agri_feature_farm_type_status
  ON crm.agri_feature (farm_id, feature_type, status);

CREATE INDEX IF NOT EXISTS idx_agri_feature_parcel_id
  ON crm.agri_feature (parcel_id);

CREATE INDEX IF NOT EXISTS idx_agri_feature_bbox
  ON crm.agri_feature USING gist (bbox);

-- ---------------------------------------------------------------------------
-- Organization and management scope
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS crm.organization (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id bigint NULL REFERENCES crm.organization(id) ON DELETE SET NULL,
  org_code text NOT NULL UNIQUE,
  org_name text NOT NULL,
  org_type text NOT NULL,
  level_no integer NOT NULL DEFAULT 1,
  path text NULL,
  status text NOT NULL DEFAULT 'active',
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_organization_parent_id
  ON crm.organization (parent_id);

CREATE TABLE IF NOT EXISTS crm.farm (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NULL REFERENCES crm.organization(id) ON DELETE SET NULL,
  farm_code text NOT NULL UNIQUE,
  farm_name text NOT NULL,
  manager_employee_id integer NULL REFERENCES crm."Employee"(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'active',
  geom geometry(MultiPolygon, 4326) NULL,
  centroid_geom geometry(Point, 4326) NULL,
  bbox geometry(Polygon, 4326) NULL,
  area_m2 double precision NULL,
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_farm_organization_id
  ON crm.farm (organization_id);

CREATE INDEX IF NOT EXISTS idx_farm_geom
  ON crm.farm USING gist (geom);

CREATE INDEX IF NOT EXISTS idx_farm_bbox
  ON crm.farm USING gist (bbox);

CREATE TABLE IF NOT EXISTS crm.farm_member (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  employee_id integer NOT NULL REFERENCES crm."Employee"(id) ON DELETE CASCADE,
  member_role text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  joined_at timestamptz NOT NULL DEFAULT now(),
  left_at timestamptz NULL,
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uk_farm_member_unique UNIQUE (farm_id, employee_id, member_role)
);

CREATE INDEX IF NOT EXISTS idx_farm_member_farm_id
  ON crm.farm_member (farm_id);

CREATE INDEX IF NOT EXISTS idx_farm_member_employee_id
  ON crm.farm_member (employee_id);

-- ---------------------------------------------------------------------------
-- Base spatial objects
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS crm.parcel (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  parcel_code text NOT NULL UNIQUE,
  parcel_name text NOT NULL,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  owner_org_id bigint NULL REFERENCES crm.organization(id) ON DELETE SET NULL,
  manager_employee_id integer NULL REFERENCES crm."Employee"(id) ON DELETE SET NULL,
  current_crop_id bigint NULL,
  land_use_type text NULL,
  soil_type text NULL,
  irrigation_type text NULL,
  cultivation_status text NULL,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  centroid_geom geometry(Point, 4326) NULL,
  bbox geometry(Polygon, 4326) NULL,
  area_m2 double precision NULL,
  perimeter_m double precision NULL,
  elevation_avg_m double precision NULL,
  slope_avg double precision NULL,
  aspect_main double precision NULL,
  latest_ndvi_dataset_id bigint NULL,
  latest_flood_result_id bigint NULL,
  latest_uav_mission_id bigint NULL,
  valid_from timestamptz NULL,
  valid_to timestamptz NULL,
  is_active boolean NOT NULL DEFAULT true,
  version_no integer NOT NULL DEFAULT 1,
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_parcel_farm_id
  ON crm.parcel (farm_id);

CREATE INDEX IF NOT EXISTS idx_parcel_owner_org_id
  ON crm.parcel (owner_org_id);

CREATE INDEX IF NOT EXISTS idx_parcel_active_valid
  ON crm.parcel (is_active, valid_from DESC, valid_to DESC);

CREATE INDEX IF NOT EXISTS idx_parcel_geom
  ON crm.parcel USING gist (geom);

CREATE INDEX IF NOT EXISTS idx_parcel_bbox
  ON crm.parcel USING gist (bbox);

CREATE INDEX IF NOT EXISTS idx_parcel_attrs
  ON crm.parcel USING gin (attrs);

CREATE TABLE IF NOT EXISTS crm.parcel_subdivision (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcel_id bigint NOT NULL REFERENCES crm.parcel(id) ON DELETE CASCADE,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  subdivision_code text NOT NULL,
  subdivision_name text NOT NULL,
  subdivision_type text NOT NULL,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  area_m2 double precision NULL,
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uk_parcel_subdivision_code UNIQUE (parcel_id, subdivision_code)
);

CREATE INDEX IF NOT EXISTS idx_parcel_subdivision_parcel_id
  ON crm.parcel_subdivision (parcel_id);

CREATE INDEX IF NOT EXISTS idx_parcel_subdivision_geom
  ON crm.parcel_subdivision USING gist (geom);

CREATE TABLE IF NOT EXISTS crm.facility (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  parcel_id bigint NULL REFERENCES crm.parcel(id) ON DELETE SET NULL,
  facility_code text NOT NULL UNIQUE,
  facility_name text NOT NULL,
  facility_type text NOT NULL,
  geom geometry(Point, 4326) NOT NULL,
  elevation_m double precision NULL,
  model_uri text NULL,
  tileset_uri text NULL,
  thumbnail_uri text NULL,
  status text NOT NULL DEFAULT 'active',
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_facility_farm_id
  ON crm.facility (farm_id);

CREATE INDEX IF NOT EXISTS idx_facility_parcel_id
  ON crm.facility (parcel_id);

CREATE INDEX IF NOT EXISTS idx_facility_geom
  ON crm.facility USING gist (geom);

CREATE TABLE IF NOT EXISTS crm.linear_asset (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  parcel_id bigint NULL REFERENCES crm.parcel(id) ON DELETE SET NULL,
  asset_code text NOT NULL UNIQUE,
  asset_name text NOT NULL,
  asset_type text NOT NULL,
  geom geometry(MultiLineString, 4326) NOT NULL,
  length_m double precision NULL,
  status text NOT NULL DEFAULT 'active',
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_linear_asset_farm_id
  ON crm.linear_asset (farm_id);

CREATE INDEX IF NOT EXISTS idx_linear_asset_parcel_id
  ON crm.linear_asset (parcel_id);

CREATE INDEX IF NOT EXISTS idx_linear_asset_geom
  ON crm.linear_asset USING gist (geom);

CREATE TABLE IF NOT EXISTS crm.water_body (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  parcel_id bigint NULL REFERENCES crm.parcel(id) ON DELETE SET NULL,
  water_body_code text NOT NULL UNIQUE,
  water_body_name text NOT NULL,
  water_body_type text NOT NULL,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  area_m2 double precision NULL,
  avg_depth_m double precision NULL,
  status text NOT NULL DEFAULT 'active',
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_water_body_farm_id
  ON crm.water_body (farm_id);

CREATE INDEX IF NOT EXISTS idx_water_body_parcel_id
  ON crm.water_body (parcel_id);

CREATE INDEX IF NOT EXISTS idx_water_body_geom
  ON crm.water_body USING gist (geom);

-- ---------------------------------------------------------------------------
-- Temporal versioning and audit
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS crm.parcel_version (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcel_id bigint NOT NULL REFERENCES crm.parcel(id) ON DELETE CASCADE,
  version_no integer NOT NULL,
  edited_by_admin_id integer NULL REFERENCES crm.admin(id) ON DELETE SET NULL,
  edit_action text NOT NULL DEFAULT 'update',
  snapshot jsonb NOT NULL,
  geom geometry(MultiPolygon, 4326) NOT NULL,
  area_m2 double precision NULL,
  valid_from timestamptz NULL,
  valid_to timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uk_parcel_version_unique UNIQUE (parcel_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_parcel_version_parcel_id
  ON crm.parcel_version (parcel_id, version_no DESC);

CREATE INDEX IF NOT EXISTS idx_parcel_version_geom
  ON crm.parcel_version USING gist (geom);

CREATE TABLE IF NOT EXISTS crm.parcel_edit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcel_id bigint NOT NULL REFERENCES crm.parcel(id) ON DELETE CASCADE,
  edited_by_admin_id integer NULL REFERENCES crm.admin(id) ON DELETE SET NULL,
  operation text NOT NULL,
  changed_fields text[] NULL,
  before_data jsonb NULL,
  after_data jsonb NULL,
  reason text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_parcel_edit_log_parcel_id
  ON crm.parcel_edit_log (parcel_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Analysis and resource attachment
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS crm.uav_mission (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  parcel_id bigint NULL REFERENCES crm.parcel(id) ON DELETE SET NULL,
  mission_code text NOT NULL UNIQUE,
  mission_name text NOT NULL,
  mission_type text NOT NULL,
  status text NOT NULL DEFAULT 'planned',
  uav_sn text NULL,
  pilot_name text NULL,
  flight_path geometry(MultiLineStringZ, 4326) NULL,
  altitude_m double precision NULL,
  started_at timestamptz NULL,
  ended_at timestamptz NULL,
  result_uri text NULL,
  attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_uav_mission_farm_id
  ON crm.uav_mission (farm_id);

CREATE INDEX IF NOT EXISTS idx_uav_mission_parcel_id
  ON crm.uav_mission (parcel_id);

CREATE INDEX IF NOT EXISTS idx_uav_mission_time
  ON crm.uav_mission (started_at DESC, ended_at DESC);

CREATE INDEX IF NOT EXISTS idx_uav_mission_flight_path
  ON crm.uav_mission USING gist (flight_path);

CREATE TABLE IF NOT EXISTS crm.ndvi_dataset (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  parcel_id bigint NULL REFERENCES crm.parcel(id) ON DELETE SET NULL,
  mission_id bigint NULL REFERENCES crm.uav_mission(id) ON DELETE SET NULL,
  dataset_code text NOT NULL UNIQUE,
  dataset_name text NOT NULL,
  acquired_at timestamptz NOT NULL,
  raster_uri text NOT NULL,
  point_cloud_uri text NULL,
  thumbnail_uri text NULL,
  preview_geom geometry(MultiPolygon, 4326) NULL,
  ndvi_min double precision NULL,
  ndvi_max double precision NULL,
  ndvi_avg double precision NULL,
  stats jsonb NOT NULL DEFAULT '{}'::jsonb,
  valid_from timestamptz NULL,
  valid_to timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ndvi_dataset_farm_id
  ON crm.ndvi_dataset (farm_id);

CREATE INDEX IF NOT EXISTS idx_ndvi_dataset_parcel_id
  ON crm.ndvi_dataset (parcel_id);

CREATE INDEX IF NOT EXISTS idx_ndvi_dataset_acquired_at
  ON crm.ndvi_dataset (acquired_at DESC);

CREATE INDEX IF NOT EXISTS idx_ndvi_dataset_preview_geom
  ON crm.ndvi_dataset USING gist (preview_geom);

CREATE TABLE IF NOT EXISTS crm.flood_analysis_result (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id bigint NULL UNIQUE REFERENCES crm.agri_feature(id) ON DELETE SET NULL,
  farm_id bigint NOT NULL REFERENCES crm.farm(id) ON DELETE CASCADE,
  parcel_id bigint NULL REFERENCES crm.parcel(id) ON DELETE SET NULL,
  source_dataset_id bigint NULL REFERENCES crm.ndvi_dataset(id) ON DELETE SET NULL,
  result_code text NOT NULL UNIQUE,
  result_name text NOT NULL,
  analysis_time timestamptz NOT NULL,
  flood_geom geometry(MultiPolygon, 4326) NULL,
  water_level_m double precision NULL,
  inundated_area_m2 double precision NULL,
  result_uri text NULL,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_flood_result_farm_id
  ON crm.flood_analysis_result (farm_id);

CREATE INDEX IF NOT EXISTS idx_flood_result_parcel_id
  ON crm.flood_analysis_result (parcel_id);

CREATE INDEX IF NOT EXISTS idx_flood_result_analysis_time
  ON crm.flood_analysis_result (analysis_time DESC);

CREATE INDEX IF NOT EXISTS idx_flood_result_geom
  ON crm.flood_analysis_result USING gist (flood_geom);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_parcel_latest_ndvi'
  ) THEN
    ALTER TABLE crm.parcel
      ADD CONSTRAINT fk_parcel_latest_ndvi
      FOREIGN KEY (latest_ndvi_dataset_id)
      REFERENCES crm.ndvi_dataset(id)
      ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_parcel_latest_flood'
  ) THEN
    ALTER TABLE crm.parcel
      ADD CONSTRAINT fk_parcel_latest_flood
      FOREIGN KEY (latest_flood_result_id)
      REFERENCES crm.flood_analysis_result(id)
      ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_parcel_latest_uav'
  ) THEN
    ALTER TABLE crm.parcel
      ADD CONSTRAINT fk_parcel_latest_uav
      FOREIGN KEY (latest_uav_mission_id)
      REFERENCES crm.uav_mission(id)
      ON DELETE SET NULL;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Cesium / map unified read view
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW crm.v_cesium_feature_feed AS
SELECT
  p.feature_id,
  'parcel'::text AS source_table,
  p.id AS source_id,
  'parcel'::text AS feature_type,
  p.farm_id,
  p.id AS parcel_id,
  p.parcel_name AS display_name,
  p.geom,
  p.valid_from,
  p.valid_to,
  NULL::text AS resource_uri,
  jsonb_build_object(
    'versionNo', p.version_no,
    'landUseType', p.land_use_type,
    'cultivationStatus', p.cultivation_status
  ) || p.attrs AS attrs
FROM crm.parcel p

UNION ALL

SELECT
  f.feature_id,
  'facility'::text,
  f.id,
  f.facility_type,
  f.farm_id,
  f.parcel_id,
  f.facility_name,
  f.geom,
  NULL::timestamptz,
  NULL::timestamptz,
  COALESCE(f.tileset_uri, f.model_uri) AS resource_uri,
  jsonb_build_object('thumbnailUri', f.thumbnail_uri) || f.attrs
FROM crm.facility f

UNION ALL

SELECT
  l.feature_id,
  'linear_asset'::text,
  l.id,
  l.asset_type,
  l.farm_id,
  l.parcel_id,
  l.asset_name,
  l.geom,
  NULL::timestamptz,
  NULL::timestamptz,
  NULL::text,
  jsonb_build_object('lengthM', l.length_m) || l.attrs
FROM crm.linear_asset l

UNION ALL

SELECT
  w.feature_id,
  'water_body'::text,
  w.id,
  w.water_body_type,
  w.farm_id,
  w.parcel_id,
  w.water_body_name,
  w.geom,
  NULL::timestamptz,
  NULL::timestamptz,
  NULL::text,
  jsonb_build_object('areaM2', w.area_m2, 'avgDepthM', w.avg_depth_m) || w.attrs
FROM crm.water_body w

UNION ALL

SELECT
  u.feature_id,
  'uav_mission'::text,
  u.id,
  u.mission_type,
  u.farm_id,
  u.parcel_id,
  u.mission_name,
  u.flight_path::geometry,
  u.started_at,
  u.ended_at,
  u.result_uri,
  jsonb_build_object('status', u.status, 'uavSn', u.uav_sn) || u.attrs
FROM crm.uav_mission u

UNION ALL

SELECT
  n.feature_id,
  'ndvi_dataset'::text,
  n.id,
  'ndvi_dataset'::text,
  n.farm_id,
  n.parcel_id,
  n.dataset_name,
  n.preview_geom::geometry,
  n.valid_from,
  n.valid_to,
  n.raster_uri,
  jsonb_build_object(
    'acquiredAt', n.acquired_at,
    'ndviMin', n.ndvi_min,
    'ndviMax', n.ndvi_max,
    'ndviAvg', n.ndvi_avg,
    'pointCloudUri', n.point_cloud_uri,
    'thumbnailUri', n.thumbnail_uri
  ) || n.stats
FROM crm.ndvi_dataset n

UNION ALL

SELECT
  fr.feature_id,
  'flood_analysis_result'::text,
  fr.id,
  'flood_result'::text,
  fr.farm_id,
  fr.parcel_id,
  fr.result_name,
  fr.flood_geom::geometry,
  fr.analysis_time,
  NULL::timestamptz,
  fr.result_uri,
  jsonb_build_object(
    'waterLevelM', fr.water_level_m,
    'inundatedAreaM2', fr.inundated_area_m2
  ) || fr.summary
FROM crm.flood_analysis_result fr;
